"use server"
import { prisma } from "@bs42/db"
import { formatError } from "@bs42/auth/server"
import { ActionResponse } from "@bs42/types"
import { isUUID } from "validator"
import { OrderStatus } from "@bs42/db/client"
import { auth } from "@/lib/auth"
import { headers } from "next/headers"
import z from "zod"
import { createOrderFormSchema } from "../zod"

export async function createOrderAction(data: z.infer<typeof createOrderFormSchema>): Promise<ActionResponse> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session) return { success: false, error: "Unauthorized" }

    const activeStoreId = session.session.activeOrganizationId
    if (!activeStoreId) return { success: false, error: "No active store" }

    const validatedData = await createOrderFormSchema.parseAsync(data)

    const exchangeRate = await prisma.exchangeRate.findFirst({
      where: { from: "USD", to: "GHS" },
      orderBy: { date: "desc" },
    })

    const rate = exchangeRate?.rate.toNumber() ?? 1

    // Validate stock for all items
    for (const item of validatedData.items) {
      if (item.storeListingVariantId) {
        const slv = await prisma.storeListingVariant.findUnique({
          where: { id: item.storeListingVariantId },
        })
        if (slv?.trackInventory && slv.stock < item.quantity) {
          return {
            success: false,
            error: `Insufficient stock for ${item.productName}`,
          }
        }
      } else {
        const sl = await prisma.storeListing.findUnique({
          where: { id: item.storeListingId },
        })
        if (sl?.trackInventory && sl.stock < item.quantity) {
          return {
            success: false,
            error: `Insufficient stock for ${item.productName}`,
          }
        }
      }
    }

    const subtotalUsd = validatedData.items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0)
    const subtotalGhs = subtotalUsd * rate
    const totalPrice = subtotalGhs + validatedData.shippingPrice + validatedData.taxPrice

    await prisma.order.create({
      data: {
        customerName: validatedData.customerName,
        customerEmail: validatedData.customerEmail,
        customerPhone: validatedData.customerPhone || null,
        userId: validatedData.userId || null,
        shippingMethod: validatedData.shippingMethod === "pickup" ? "PICKUP" : "DELIVERY",
        shippingName: validatedData.shippingName || null,
        shippingPhone: validatedData.shippingPhone || null,
        shippingLine1: validatedData.shippingLine1 || null,
        shippingLine2: validatedData.shippingLine2 || null,
        shippingRegion: validatedData.shippingRegion || null,
        shippingTown: validatedData.shippingTown || null,
        shippingLat: validatedData.shippingLat || null,
        shippingLng: validatedData.shippingLng || null,
        paymentMethod: "CASH",
        paymentStatus: "PENDING",
        status: "PENDING",
        subtotalUsd,
        subtotalGhs,
        shippingPrice: validatedData.shippingPrice,
        taxPrice: validatedData.taxPrice,
        totalPrice,
        currency: "GHS",
        exchangeRate: rate,
        createdById: session.user.id,
        notes: validatedData.notes || null,
        reference: "", // generated by Prisma extension
        orderItems: {
          create: validatedData.items.map((item) => ({
            organizationId: activeStoreId,
            storeListingId: item.storeListingId,
            storeListingVariantId: item.storeListingVariantId || null,
            quantity: item.quantity,
            unitPrice: item.unitPrice,
            totalPrice: item.unitPrice * item.quantity,
            productName: item.productName,
            productSlug: item.productSlug,
            productImage: item.productImage || null,
            variantDescription: item.variantDescription || null,
            sku: item.sku || null,
            storeName: item.storeName,
          })),
        },
        statusHistory: {
          create: {
            status: "PENDING",
            note: "Order created via admin portal",
            changedById: session.user.id,
          },
        },
      },
    })

    return { success: true }
  } catch (error) {
    console.log(error)
    return { success: false, error: formatError(error) }
  }
}

export const updateOrderStatusAction = async (orderId: string, status: OrderStatus, note?: string): Promise<ActionResponse> => {
  try {
    if (!orderId || !isUUID(orderId)) return { success: false, error: "Missing or invalid order ID." }

    const session = await auth.api.getSession({ headers: await headers() })
    if (!session) return { success: false, error: "Unauthorized" }

    await prisma.$transaction(async (tx) => {
      await tx.order.update({
        where: { id: orderId },
        data: {
          status,
          // Mark as paid when status is CONFIRMED for cash orders
          ...(status === "CONFIRMED" && {
            paymentStatus: "PAID",
            paidAt: new Date(),
          }),
        },
      })

      await tx.orderStatusHistory.create({
        data: {
          orderId,
          status,
          note: note || null,
          changedById: session.user.id,
        },
      })

      // Decrement stock when confirmed
      if (status === "CONFIRMED") {
        const order = await tx.order.findUnique({
          where: { id: orderId },
          include: { orderItems: true },
        })

        for (const item of order?.orderItems ?? []) {
          if (item.storeListingVariantId) {
            await tx.storeListingVariant.update({
              where: { id: item.storeListingVariantId },
              data: { stock: { decrement: item.quantity } },
            })
          } else {
            await tx.storeListing.update({
              where: { id: item.storeListingId },
              data: { stock: { decrement: item.quantity } },
            })
          }
        }
      }

      // Restore stock when cancelled or refunded
      if (status === "CANCELLED" || status === "REFUNDED") {
        const order = await tx.order.findUnique({
          where: { id: orderId },
          include: { orderItems: true },
        })

        for (const item of order?.orderItems ?? []) {
          if (item.storeListingVariantId) {
            await tx.storeListingVariant.update({
              where: { id: item.storeListingVariantId },
              data: { stock: { increment: item.quantity } },
            })
          } else {
            await tx.storeListing.update({
              where: { id: item.storeListingId },
              data: { stock: { increment: item.quantity } },
            })
          }
        }
      }
    })

    return { success: true }
  } catch (error) {
    return { success: false, error: formatError(error) }
  }
}
