export const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif"]

export const GEODATA = [
  {
    name: "Ahafo",
    towns: ["Bechem", "Duayaw Nkwantah", "Goaso", "Hwidiem", "Kenyasi", "Kukuom"],
  },
  {
    name: "Ashanti",
    towns: [
      "Abrepo Junction",
      "Abuakwa",
      "Adum",
      "Afrancho",
      "Agogo",
      "Agona",
      "Ahodwo",
      "Airport",
      "Akumadan",
      "Amakom",
      "Aputuogya",
      "Asafo",
      "Ash-Town",
      "Asokore Mampong",
      "Asokwa",
      "Asuofia",
      "Atonsu",
      "Ayeduasi",
      "Ayigya",
      "Bantama",
      "Barekese",
      "Bekwai",
      "Boadi",
      "Bomso",
      "Breman",
      "Brewery",
      "Buoho",
      "Buokrom Estate",
      "Daban",
      "Dakwadwom",
      "Deduako",
      "Denyame",
      "Effiduase",
      "Ejisu",
      "Ejura",
      "Emina",
      "Esreso",
      "Fawode",
      "Gyinyasi",
      "Jachie Pramso",
      "Kaasi",
      "KNUST",
      "Kodie",
      "Komfo Anokye",
      "Konongo",
      "Kotei",
      "Krofrom",
      "Kumasi",
      "Maakro",
      "Mampong",
      "Mankranso",
      "Manso Nkwanta",
      "Nkawie",
      "North Suntreso",
      "Nyinahin",
      "Obuasi",
      "Oforikrom",
      "Pankrono",
      "Santasi",
      "Sokoban",
      "South Suntreso",
      "Suame",
      "Tafo",
      "Takwa-Maakro",
      "Tanoso",
      "Tepa",
      "TUC",
    ],
  },
  {
    name: "Bono",
    towns: [
      "Amomaso",
      "Banda Ahenkro",
      "Berekum",
      "Benkasa",
      "Chiraa",
      "Dormaa Ahenkro",
      "Dormaa Akwamu",
      "Drobo",
      "Fiapre",
      "Jinijini",
      "New Drobo",
      "Nkrankwanta",
      "Nsawkaw",
      "Nsuatre",
      "Odumase",
      "Sampa",
      "Seikwa",
      "Sunyani",
      "Wamfie",
    ],
  },
  {
    name: "Bono East",
    towns: ["Atebubu", "Buipe", "Jema", "Kintampo", "Kwame Danso", "Nkoranza", "Prang", "Techiman", "Tuobodom", "Wenchi", "Yeji"],
  },
  {
    name: "Central",
    towns: [
      "Agona Swedru",
      "Amanfrom",
      "Anomabu",
      "Apam",
      "Bawjiase",
      "Breman Asikuma",
      "Budumburam",
      "Cape Coast",
      "Domeabra",
      "Elmina",
      "Foso",
      "Kasoa Ofaakor",
      "Kasoa Zongo",
      "Liberia Camp",
      "Mankessim",
      "Millennium City",
      "Mumford",
      "Nyakrom",
      "Nyananor",
      "Nyanyano",
      "Oduponkpehe",
      "Opeikuma",
      "Pentecost Seminary",
      "Saltpond",
      "Winneba",
    ],
  },
  {
    name: "Eastern",
    towns: [
      "Abetifi",
      "Abompe",
      "Aburi",
      "Adeiso",
      "Adjeiikrom",
      "Adukrom",
      "Ahwerease",
      "Akim Oda",
      "Akim Swedru",
      "Akosombo",
      "Akropong",
      "Akwatia",
      "Akyem Hemang",
      "Amanokrom",
      "Apirede",
      "Asamankese",
      "Asesewa",
      "Atimpoku",
      "Ayiensu",
      "Begoro",
      "Bepoase",
      "Bisibom",
      "Bososo",
      "Brekusu",
      "Coaltar",
      "Dawu",
      "Dedesoworako",
      "Donkorkrom",
      "Dwenase",
      "Gyankama",
      "Juaso",
      "Kade",
      "Kibi",
      "Kitase",
      "Koforidua",
      "Kwabeng",
      "Mamfe",
      "Mampong",
      "Mpraeso",
      "New Abirem",
      "Nkawkaw",
      "Nsawam",
      "Nsutam",
      "Obooho",
      "Obosomase",
      "Odumase Krobo",
      "Ofoase",
      "Osino",
      "Peduase",
      "Saaman",
      "Somanya",
      "Summer",
      "Suhum",
      "Tease",
      "Tutu",
    ],
  },
  {
    name: "Greater Accra",
    towns: [
      "Abelemkpe",
      "Ablekuma",
      "Abokobi",
      "Abossey Okai",
      "Accra Newtown",
      "Achimota",
      "Adabraka",
      "Adenta",
      "Afienya",
      "Agbogba",
      "Airport",
      "Amasaman",
      "Ashiaman",
      "Ashongman",
      "Aslyum Down",
      "Atico",
      "Baatsona - Spintex",
      "Bortianor",
      "Cantonment",
      "Dansoman",
      "Darkuman",
      "Dawhenya",
      "Dodowa",
      "Dome",
      "Dzorwulu",
      "East Legon",
      "Gbawe",
      "Haatso",
      "James Town",
      "Kanda",
      "Kaneshie",
      "Kasoa",
      "Kissieman",
      "Kokrobite",
      "Korle Bu",
      "Kpone",
      "Kwabenya",
      "Kwashieman",
      "Labadi",
      "Labone",
      "Lapaz",
      "Lartebiokorshie",
      "Lashibi",
      "Legon",
      "Madina",
      "Makola",
      "Mallam",
      "McCarthy Hill",
      "Michel Camp",
      "Nima",
      "Nungua",
      "Oblogo Mallam",
      "Odoponkpehe",
      "Odorkor",
      "Osu",
      "Oyarifa",
      "Patang",
      "Prampram",
      "Ridge",
      "Roman Ridge",
      "Sakumono",
      "Santa Maria",
      "Sowutuom",
      "Taifa",
      "Tema",
      "Tema New Town",
      "Tesano",
      "Teshie",
      "Tetegu",
      "Tieman",
      "Tudu",
      "Weija",
      "Westhills",
    ],
  },
  {
    name: "North East",
    towns: ["Chereponi", "Gambaga", "Nalerigu", "Walewale"],
  },
  {
    name: "Northern",
    towns: ["Bimbila", "Gushiegu", "Kpandae", "Saboba", "Salaga", "Tamale", "Tatale", "Wulensi", "Yendi"],
  },
  {
    name: "Oti",
    towns: ["Chinderi", "Jasikan", "Kadjebi", "Kete Krachi", "Kpassa", "Nkonya"],
  },
  {
    name: "Savannah",
    towns: ["Bole", "Buipe", "Damango", "Salaga", "Sawla", "Tolon"],
  },
  {
    name: "Upper East",
    towns: ["Bawku", "Bolgatanga", "Bongo", "Navrongo", "Paga", "Tongo"],
  },
  {
    name: "Upper West",
    towns: ["Funsi", "Gwollu", "Issa", "Jirapa", "Kaleo", "Lambussie", "Lawra", "Nadowli", "Nandom", "Tumu", "Wa", "Wechiau"],
  },
  {
    name: "Volta",
    towns: ["Adaklu Waya", "Adidome", "Aflao", "Agbozume", "Akatsi", "Ave Dakpa", "Ho.", "Hohoe", "Keta", "klikor", "Kpando", "Kpetoe", "Kpeve", "Sogakope"],
  },
  {
    name: "Western",
    towns: [
      "Abase",
      "Aboso",
      "Adiawoso",
      "Adiembra",
      "Adwowa",
      "Agona Nkwanta",
      "Agufo",
      "Ahonozo",
      "Akatachi",
      "Alabokazo",
      "Anaji",
      "Apowa",
      "Apremodo",
      "Asankragua",
      "Awukyere",
      "Axim",
      "Beahu",
      "Bogoso",
      "Butumagyabu",
      "Busua",
      "Daboase",
      "Dadwen",
      "Diabene",
      "Dixcove",
      "East Tanokrom",
      "Effiakuma",
      "Eikwe",
      "Elubo",
      "Essiama",
      "Essikado",
      "Essipong",
      "Ewusiejo",
      "Fijai",
      "Funko",
      "Half Assini",
      "Hotopo",
      "Inchaban",
      "kansaworado",
      "Kejabil",
      "Kojokrom",
      "Kwawkrom",
      "Kweikuma",
      "kwesimintsim",
      "Manso",
      "Miemia",
      "Mpintsin",
      "New Akwidaa",
      "New Amanfu",
      "New Takoradi",
      "Ngyiresia",
      "Nkroful",
      "Nsein",
      "Ntankoful",
      "Nzulezo",
      "Old Akwidaa",
      "Prestea",
      "Princess Town",
      "Samreboi",
      "Sekondi",
      "Shama",
      "Takoradi",
      "Tarkwa",
      "Tikobo No.1",
      "Tikobo No.2",
      "West Tanokrom",
      "Windy Ridge",
    ],
  },
  {
    name: "Western North",
    towns: [
      "Attankona",
      "Nkatieso",
      "Abochia",
      "Abusam-kwawu",
      "Achimfo",
      "Acquai Allah",
      "Adabokrom",
      "Adamase",
      "Adiembra",
      "Adjakaa",
      "Adjoafua",
      "Adukrom",
      "Afere",
      "Aferewa",
      "Agya Mensahkrom",
      "Ahibenso",
      "Akaaso",
      "Akaatiso",
      "Akontombra",
      "Akronsu",
      "Amadukrom",
      "Amoaya",
      "Amonie",
      "Anhwiafutu",
      "Anhwiaso",
      "Ankra-Muano",
      "Antobia",
      "Apronsee Mission",
      "Asawinso",
      "Asemkrom",
      "Asikrom (Ensonnyameye)",
      "Asuontaa",
      "Asuopiri",
      "Awaso",
      "Ayidam",
      "Benchema",
      "Benomsuo",
      "Bethlehem",
      "Bibiani",
      "Bibiani",
      "Bodi",
      "Boison",
      "Boizan",
      "Bokabo",
      "Bonsu Nkwanta",
      "Car Owner",
      "Chirano",
      "Dadieso",
      "Denchemuosue",
      "Disueano",
      "Dominibo",
      "Elluokrom",
      "Enchi",
      "Enchi",
      "Essam Debiso",
      "Goka",
      "Gyema",
      "Hene Nkwanta",
      "Homgyebre",
      "Hwenampori",
      "Jensue",
      "Juabeso Nkwanta",
      "Juabeso",
      "Juaboso",
      "kaase",
      "Kakanabo",
      "Kama",
      "Kankyiabo",
      "Kantakrobo",
      "Kefass",
      "Kofi Krah",
      "Kofikrom",
      "Kojoaba",
      "Kojofosukrom",
      "Kotosaa",
      "Kramokrom",
      "Kunkumso",
      "Kwafukaa",
      "Kwaku Kyerekrom",
      "Kwame Adjei Krom",
      "Kwamebikrom",
      "Kwawu",
      "Kwesikrom",
      "Kyerkyewere",
      "Mafia",
      "Mangoase-Punpunso",
      "Mangoase",
      "Mayera",
      "Moshiehene Krom",
      "New Abesim",
      "New Achiase",
      "New Nsuatre",
      "New Yakasi",
      "Nkrabea",
      "Nkwanta",
      "Nso Nyame Ye (Mireku)",
      "Nsowakrom",
      "Ntesano",
      "Nyamebekyere No.1",
      "Nyankamam",
      "Okrayawkrom",
      "Old Debiso",
      "Old Yakasi",
      "Omanpe",
      "Oseikojokrom",
      "Osumanikrom",
      "Owusu Krom",
      "Patakro",
      "Pramprase",
      "Proso",
      "Sayerano",
      "Sefwi Anhwiaso",
      "Sefwi Bekwai",
      "Sewum",
      "Sonka No.1",
      "Subri Nkwanta (Kojina)",
      "Subri",
      "Suiano",
      "Surano",
      "Tanoso-Praso",
      "Wenchi",
      "Yawmatwa",
      "Yiwabra",
    ],
  },
]
