// constants.ts
import { Status } from "./generated/prisma/enums"

export const categories = [
  // ==================== ROOT CATEGORIES ====================
  {
    name: "Security",
    description: "Security solutions including CCTV, access control, and alarms",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1683805029514.png",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "security_root",
  },
  {
    name: "Networking",
    description: "Networking infrastructure and devices",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1683903019320.jpg",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "networking_root",
  },
  {
    name: "Smart Homes",
    description: "Smart home automation devices and systems",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1689349405409.webp",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "smart_homes_root",
  },
  {
    name: "Computing",
    description: "Computers and computing accessories",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1691257250688.jpg",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "computing_root",
  },
  {
    name: "Telephony",
    description: "Telephone and VoIP solutions",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "telephony_root",
  },
  {
    name: "Tools & Home Improvement",
    description: "Tools and home improvement products",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: null,
    ref: "tools_home_root",
  },

  // ==================== LEVEL 2 - SECURITY ====================
  {
    name: "CCTV",
    description: "Closed-circuit television cameras and recording systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "security_root",
    ref: "cctv",
  },
  {
    name: "Access Control",
    description: "Access control systems and components",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "security_root",
    ref: "access_control",
  },
  {
    name: "Alarms",
    description: "Fire and intruder alarm systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "security_root",
    ref: "alarms",
  },

  // ==================== LEVEL 2 - NETWORKING ====================
  {
    name: "Infrastructure",
    description: "Networking infrastructure components",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_root",
    ref: "infrastructure",
  },
  {
    name: "Networking Devices",
    description: "Active networking devices",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_root",
    ref: "networking_devices",
  },
  {
    name: "Cables",
    description: "Various types of cables",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_root",
    ref: "cables",
  },

  // ==================== LEVEL 2 - SMART HOMES ====================
  {
    name: "Smart Devices",
    description: "Smart home devices and accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_homes_root",
    ref: "smart_devices",
  },
  {
    name: "Control Systems",
    description: "Smart home control panels and gateways",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_homes_root",
    ref: "control_systems",
  },

  // ==================== LEVEL 2 - COMPUTING ====================
  {
    name: "Computers & Accessories",
    description: "Computers and computer accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "computing_root",
    ref: "computers_accessories",
  },

  // ==================== LEVEL 2 - TELEPHONY ====================
  {
    name: "VOIP",
    description: "Voice over IP phones and systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "telephony_root",
    ref: "voip",
  },

  // ==================== LEVEL 2 - TOOLS & HOME ====================
  {
    name: "Electrical",
    description: "Electrical tools and equipment",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "tools_home_root",
    ref: "electrical",
  },
  {
    name: "Plumbing",
    description: "Plumbing tools and supplies",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "tools_home_root",
    ref: "plumbing",
  },
  {
    name: "Home Improvement",
    description: "Home improvement products",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "tools_home_root",
    ref: "home_improvement",
  },

  // ==================== LEVEL 3 - CCTV ====================
  {
    name: "CCTV Cameras",
    description: "Surveillance cameras",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cctv",
    ref: "cctv_cameras",
  },
  {
    name: "CCTV Recorders",
    description: "DVR and NVR recorders",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cctv",
    ref: "cctv_recorders",
  },
  {
    name: "CCTV Accessories",
    description: "CCTV mounting brackets, power supplies, and accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cctv",
    ref: "cctv_accessories",
  },
  {
    name: "CCTV Installation Packages",
    description: "Complete CCTV installation kits",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cctv",
    ref: "cctv_installation_packages",
  },

  // ==================== LEVEL 3 - ACCESS CONTROL ====================
  {
    name: "Card Readers",
    description: "Access control card readers",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "card_readers",
  },
  {
    name: "Electronic Locks",
    description: "Electronic and magnetic locks",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "electronic_locks",
  },
  {
    name: "Exit Buttons",
    description: "Exit buttons and call points",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "exit_buttons",
  },
  {
    name: "Intercoms",
    description: "Audio and video intercom systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "intercoms",
  },
  {
    name: "Power Supplies",
    description: "Access control power supplies",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "access_control_power_supplies",
  },
  {
    name: "Accessories",
    description: "Access control accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "access_control",
    ref: "access_control_accessories",
  },

  // ==================== LEVEL 3 - ALARMS ====================
  {
    name: "Fire Alarms",
    description: "Fire alarm systems and detectors",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "alarms",
    ref: "fire_alarms",
  },
  {
    name: "Intruder Alarms",
    description: "Burglar and intrusion alarm systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "alarms",
    ref: "intruder_alarms",
  },

  // ==================== LEVEL 3 - INFRASTRUCTURE ====================
  {
    name: "Network Infrastructure",
    description: "Network infrastructure components",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "infrastructure",
    ref: "network_infrastructure",
  },
  {
    name: "Cable Management",
    description: "Cable management solutions",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "infrastructure",
    ref: "cable_management",
  },

  // ==================== LEVEL 3 - NETWORKING DEVICES ====================
  {
    name: "Network Switches",
    description: "Network switches and hubs",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_devices",
    ref: "network_switches",
  },
  {
    name: "Routers & Gateways",
    description: "Routers and network gateways",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_devices",
    ref: "routers_gateways",
  },
  {
    name: "Wireless Accessories",
    description: "Wireless aerials and accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_devices",
    ref: "wireless_accessories",
  },
  {
    name: "Network Cabinets",
    description: "Network equipment cabinets and racks",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_devices",
    ref: "network_cabinets",
  },
  {
    name: "Network Tools",
    description: "Network and electronic tools",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "networking_devices",
    ref: "network_tools",
  },

  // ==================== LEVEL 3 - CABLES ====================
  {
    name: "Network Cables",
    description: "Ethernet and network cables",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1699559662088.jpg",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cables",
    ref: "network_cables",
  },
  {
    name: "Audio & Video Cables",
    description: "Audio and video cables",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cables",
    ref: "audio_video_cables",
  },
  {
    name: "Power Cables",
    description: "Power and electrical cables",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cables",
    ref: "power_cables",
  },
  {
    name: "Plugs & Connectors",
    description: "Network plugs and connectors",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cables",
    ref: "plugs_connectors",
  },
  {
    name: "Modules & Faceplates",
    description: "Network modules and faceplates",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "cables",
    ref: "modules_faceplates",
  },

  // ==================== LEVEL 3 - SMART DEVICES ====================
  {
    name: "Smart Lights",
    description: "Smart lighting systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "smart_lights",
  },
  {
    name: "Smart Switches",
    description: "Smart light switches and dimmers",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "smart_switches",
  },
  {
    name: "Smart Plugs",
    description: "Smart plugs and sockets",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "smart_plugs",
  },
  {
    name: "Smart Locks",
    description: "Smart door locks",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1705693109731.jpg",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "smart_locks",
  },
  {
    name: "Smart Curtains",
    description: "Smart curtain and blind controllers",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "smart_curtains",
  },
  {
    name: "Motion Sensors",
    description: "Motion and occupancy sensors",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "motion_sensors",
  },
  {
    name: "LED Accessories",
    description: "LED strip controllers and accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "smart_devices",
    ref: "led_accessories",
  },

  // ==================== LEVEL 3 - CONTROL SYSTEMS ====================
  {
    name: "Control Panels",
    description: "Smart home control panels",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "control_systems",
    ref: "control_panels",
  },
  {
    name: "Gateways & Hubs",
    description: "Smart home gateways and hubs",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "control_systems",
    ref: "gateways_hubs",
  },
  {
    name: "Indoor Stations",
    description: "Indoor stations for intercoms",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "control_systems",
    ref: "indoor_stations",
  },

  // ==================== LEVEL 3 - COMPUTERS & ACCESSORIES ====================
  {
    name: "Data Storage",
    description: "External drives and storage devices",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "computers_accessories",
    ref: "data_storage",
  },
  {
    name: "USB Drives",
    description: "USB flash drives",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "computers_accessories",
    ref: "usb_drives",
  },
  {
    name: "Printers",
    description: "Printers and printing accessories",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "computers_accessories",
    ref: "printers",
  },
  {
    name: "Thermal Printers",
    description: "Thermal label and receipt printers",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "printers",
    ref: "thermal_printers",
  },

  // ==================== LEVEL 3 - VOIP ====================
  {
    name: "IP Phones",
    description: "Cloud IP phones",
    image: "https://bs42shopstorage.blob.core.windows.net/pictures/1685543478424.png",
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "voip",
    ref: "ip_phones",
  },

  // ==================== LEVEL 3 - ELECTRICAL ====================
  {
    name: "Solar Products",
    description: "Solar water heaters and solar products",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "electrical",
    ref: "solar_products",
  },
  {
    name: "Water Pumps",
    description: "Water pumps and systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "electrical",
    ref: "water_pumps",
  },
  {
    name: "Speakers",
    description: "Audio speakers and sound systems",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "electrical",
    ref: "speakers",
  },
  {
    name: "Tools",
    description: "Electrical and general tools",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "electrical",
    ref: "tools",
  },

  // ==================== LEVEL 3 - PLUMBING ====================
  {
    name: "Plumbing Supplies",
    description: "Plumbing tools and supplies",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "plumbing",
    ref: "plumbing_supplies",
  },

  // ==================== LEVEL 3 - HOME IMPROVEMENT ====================
  {
    name: "Floor & Wall",
    description: "Flooring and wall products",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "home_improvement",
    ref: "floor_wall",
  },
  {
    name: "Home Accessories",
    description: "Home accessories and decor",
    image: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
    parentRef: "home_improvement",
    ref: "home_accessories",
  },
]

export const brands = [
  {
    name: "British General",
    website: "https://www.bgelectrical.uk/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1683804075632.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "BS42.Net",
    website: "https://www.bs42.net",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684154588341.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Mikrotik",
    website: "https://mikrotik.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684231003232.jpg",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Comfast",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684238520468.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Fanvil",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684251495857.webp",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Ubiquiti",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684315605167.jpg",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Tuya",
    website: "https://www.tuya.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1684424197486.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Cisco",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1685540342867.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Panasonic",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1685540434341.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Omada",
    website: "",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1690283576604.png",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Lanbon",
    website: "https://www.lanbon.cn/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1692024233124.webp",
    description: null,
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Yealink",
    website: "https://www.yealink.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/testpictures/1694689743178.png",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "GZCOM",
    website: "https://www.gzcomm.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1697488506680.jpg",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "SIEMENS",
    website: "https://www.siemens.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1701293740561.jpg",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "ZISA",
    website: "https://www.zisacom.com",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1701991742176.jpg",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Mestek",
    website: "http://www.mestek-tools.com/",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1724351316129.jpg",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Ifan",
    website: "http://www.bs42.net",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1747137397614.png",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "Satlink",
    website: "http://www.bs42.net",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1747137778968.png",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "D'Locks",
    website: "http://www.bs42.net",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1753798519478.png",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
  {
    name: "TT Lock",
    website: "http://www.bs42.net",
    logo: "https://bs42shopstorage.blob.core.windows.net/pictures/1758099684874.webp",
    description: "",
    status: "PUBLISHED" as Status,
    isFeatured: false,
  },
]
